#!/usr/bin/bash

operatingSystem=$(hostnamectl | grep "Operating System")

if [[ "${operatingSystem}" == *"Ubuntu"* ]]; then
  echo "OS: Ubuntu - Updating..."
  sudo apt update && sudo apt upgrade
elif [[ "${operatingSystem}" == *"Fedora"* ]]; then
  echo "OS: Fedora - Updating..."
  sudo dnf upgrade
fi
