---
- name: Update packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: latest

- name: add custom bash prompt to .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.bashrc
    regexp: '\Z'
    line: "{{ custom_bashrc }}"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy update file
  copy:
    src: files/update
    dest: /bin/update
    owner: root
    group: root
    mode: 0755
