---
### Install on Fedora
  - name: install VS Code repo (dnf)
    become: yes
    yum_repository:
      name: code
      description: Visual Studio Code repo
      file: vscode
      baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
      gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
      gpgcheck: yes
    when: ansible_facts['distribution'] == "Fedora"

  - name: install VS Code (dnf)
    become: yes
    dnf:
      name: code
      state: present
