---
- name: Configure dnf
  ansible.builtin.copy:
    src: files/dnf.conf
    dest: /etc/dnf/dnf.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['distribution'] == "Fedora"

- name: Update packages on Ubuntu
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Upgrade all packages on Fedora
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_facts['distribution'] == "Fedora"

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: latest

- name: Copy bashrc file
  copy:
    src: files/.bashrc
    dest: "/home/{{ username }}/.bashrc"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Copy update file
  copy:
    src: files/update
    dest: /bin/update
    owner: root
    group: root
    mode: 0755

- name: Copy backup file
  copy:
    src: files/backup.sh
    dest: /bin/backup.sh
    owner: root
    group: root
    mode: 0755

- name: Configure backup cron
  become: no
  ansible.builtin.cron:
    name: "Perform backup"
    minute: "*/30"
    job: "/bin/backup.sh"

- name: Copy virus scan file
  copy:
    src: files/av_scan.sh
    dest: /bin/av_scan.sh
    owner: root
    group: root
    mode: 0755

- name: Configure virus scan cron
  become: yes
  ansible.builtin.cron:
    name: "Perform virus scan"
    hour: "11"
    minute: "00"
    weekday: "6"
    job: "/bin/av_scan.sh"
