---
- name: Add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present

- name: Install the handbrake flatpak
  community.general.flatpak:
    name: fr.handbrake.ghb
    state: present

- name: Install the discord flatpak
  community.general.flatpak:
    name: com.discordapp.Discord
    state: present

- name: Install the Thunderbird flatpak
  community.general.flatpak:
    name: org.mozilla.Thunderbird
    state: present
  
